### ISSUE TITLE
[Proposal] 使用 XML 定义卡片消息

### ISSUE THREAD

**Issue by LiamSho** [gehongyan/Kook.Net#8]
卡片消息这类渲染成 UI 的组件，使用 XML 语言定义比较直观（类似于 HTML、XAML）。相比使用 CardBuilder，使用 XML 文件来定义还可以在不改动代码的情况下修改预定义的卡片。对于需要运行时才能决定的值，可以使用 Liquid Template 对 XML 进行修改。

目前已经实现了使用 XSD 来定义 XML 格式，和将 XML 反序列化至 `List<ICard>`

- [XSD](https://github.com/LiamSho/Kook.Net/blob/master/spec/card-message.xsd)
- [Example 1](https://github.com/LiamSho/Kook.Net/blob/master/spec/examples/vote.xml)
- [Example 2](https://github.com/LiamSho/Kook.Net/blob/master/spec/examples/weibo.xml)
- [Deserializer](https://github.com/LiamSho/Kook.Net/blob/master/src/Kook.Net.CardMarkup/CardMarkupSerializer.cs)

如果觉得可以我再发起 PR

**Comment by gehongyan** [comment]
很棒！感谢提议！欢迎 PR！
